### ISSUE TITLE
Problem with location of hubs assembly

### ISSUE THREAD

**Issue by MaldaCR** [yetanotherchris/SignalrTypescriptGenerator#3]
Hi,
nice tool, but I have some problem with generating of TS proxy if .NET assembly containing the hubs, is located somewhere else than SignalrTypescriptGenerator.exe. e.g. if I use cmd line: SignalrTypescriptGenerator.exe -a "C:\WORK\ZZ\webapp.dll" -o "c:\work
\zz\srv.ts" it works only when SignalrTypescriptGenerator.exe is located in C:\WORK\ZZ folder. Otherwise the generated srv.ts is "emty". I have tried to locate the problem but I got lost on _hubmanager.GetHubs() - line 57 in SignalrHubinator.cs, which does'n find any hub in webapp.dll. webapp.dll is loaded to the current domain inside LoadAssemblyIntoAppDomain(), but any hub is find inside it. As I mentioned, if I put exe and dll to the same folder it's working well. Am I missing something ?

**Comment by yetanotherchris** [comment]
You can change that by forking and altering this line if you need:

https://github.com/yetanotherchris/SignalrTypescriptGenerator/blob/master/src/SignalrTypescriptGenerator/Program.cs#L51

Change the `AssemblyPath` to whatever you need
